# Generated by Django 5.2.4 on 2025-07-28 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField(choices=[('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00'), ('23:00', '23:00'), ('00:00', '00:00')])),
            ],
            options={
                'ordering': ['horario'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('dni', models.IntegerField(unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo del responsable')),
                ('dni', models.IntegerField(verbose_name='DNI del responsable')),
                ('comensales', models.IntegerField(verbose_name='Numero de comensales')),
                ('fecha', models.DateField()),
                ('horario', models.ManyToManyField(to='res.bloquehorario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.usuario', verbose_name='Creador de la reserva')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
