# Generated by Django 5.2.4 on 2025-08-01 16:47

from django.db import migrations


def crear_bloques_horarios(apps,schema_editor):
    BloqueHorario = apps.get_model('res', 'BloqueHorario')
    for bloque in ['18:00','19:00','20:00','21:00','22:00','23:00','00:00']:
        BloqueHorario.objects.get_or_create(horario=bloque)
    

class Migration(migrations.Migration):

    dependencies = [
        ('res', '0002_rename_reserva_reservamodel_delete_usuario_and_more'),
    ]

    operations = [
        migrations.RunPython(crear_bloques_horarios)
    ]
